name: build

on:
  push:
    branches:
      - main
      - release

  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run code style check
        run: npm run style:check

      - name: Run tests
        run: npm test

      - name: Run audit
        run: npm audit --production
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install semantic-release plugins
        run: npm install --no-save @semantic-release/exec conventional-changelog-conventionalcommits

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ github.token }}
